version: '3'
services:
  test_task_staply:
    build:
      context: .
    volumes:
      - "./docker-data:/go/src/github.com/stixlink/test_task_staply"
    ports:
      - "58001:58001"
    environment:
      - MY_SERVER_PORT=58001
    entrypoint:
      - "/go/bin/test_task_staply"
      - "-save-dir=./"
