// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stixlink/test_task_go_staply/iface (interfaces: ImageResizer,ImageValidator,Namer,Downloader)

package main_mocks

import (
	"github.com/golang/mock/gomock"
	"net/url"
	"os"
	"reflect"
)

// MockImageResizer is a mock of ImageResizer interface
type MockImageResizer struct {
	ctrl     *gomock.Controller
	recorder *MockImageResizerMockRecorder
}

// MockImageResizerMockRecorder is the mock recorder for MockImageResizer
type MockImageResizerMockRecorder struct {
	mock *MockImageResizer
}

// NewMockImageResizer creates a new mock instance
func NewMockImageResizer(ctrl *gomock.Controller) *MockImageResizer {
	mock := &MockImageResizer{ctrl: ctrl}
	mock.recorder = &MockImageResizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockImageResizer) EXPECT() *MockImageResizerMockRecorder {
	return _m.recorder
}

// Resize mocks base method
func (_m *MockImageResizer) Resize(_param0 *os.File, _param1 *os.File, _param2 uint, _param3 uint) error {
	ret := _m.ctrl.Call(_m, "Resize", _param0, _param1, _param2, _param3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resize indicates an expected call of Resize
func (_mr *MockImageResizerMockRecorder) Resize(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Resize", reflect.TypeOf((*MockImageResizer)(nil).Resize), arg0, arg1, arg2, arg3)
}

// MockImageValidator is a mock of ImageValidator interface
type MockImageValidator struct {
	ctrl     *gomock.Controller
	recorder *MockImageValidatorMockRecorder
}

// MockImageValidatorMockRecorder is the mock recorder for MockImageValidator
type MockImageValidatorMockRecorder struct {
	mock *MockImageValidator
}

// NewMockImageValidator creates a new mock instance
func NewMockImageValidator(ctrl *gomock.Controller) *MockImageValidator {
	mock := &MockImageValidator{ctrl: ctrl}
	mock.recorder = &MockImageValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockImageValidator) EXPECT() *MockImageValidatorMockRecorder {
	return _m.recorder
}

// Validate mocks base method
func (_m *MockImageValidator) Validate(_param0 []byte) (bool, error) {
	ret := _m.ctrl.Call(_m, "Validate", _param0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate
func (_mr *MockImageValidatorMockRecorder) Validate(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Validate", reflect.TypeOf((*MockImageValidator)(nil).Validate), arg0)
}

// MockNamer is a mock of Namer interface
type MockNamer struct {
	ctrl     *gomock.Controller
	recorder *MockNamerMockRecorder
}

// MockNamerMockRecorder is the mock recorder for MockNamer
type MockNamerMockRecorder struct {
	mock *MockNamer
}

// NewMockNamer creates a new mock instance
func NewMockNamer(ctrl *gomock.Controller) *MockNamer {
	mock := &MockNamer{ctrl: ctrl}
	mock.recorder = &MockNamerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockNamer) EXPECT() *MockNamerMockRecorder {
	return _m.recorder
}

// CreateName mocks base method
func (_m *MockNamer) CreateName(_param0 string, _param1 string, _param2 []string) (string, []string) {
	ret := _m.ctrl.Call(_m, "CreateName", _param0, _param1, _param2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]string)
	return ret0, ret1
}

// CreateName indicates an expected call of CreateName
func (_mr *MockNamerMockRecorder) CreateName(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CreateName", reflect.TypeOf((*MockNamer)(nil).CreateName), arg0, arg1, arg2)
}

// MockDownloader is a mock of Downloader interface
type MockDownloader struct {
	ctrl     *gomock.Controller
	recorder *MockDownloaderMockRecorder
}

// MockDownloaderMockRecorder is the mock recorder for MockDownloader
type MockDownloaderMockRecorder struct {
	mock *MockDownloader
}

// NewMockDownloader creates a new mock instance
func NewMockDownloader(ctrl *gomock.Controller) *MockDownloader {
	mock := &MockDownloader{ctrl: ctrl}
	mock.recorder = &MockDownloaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockDownloader) EXPECT() *MockDownloaderMockRecorder {
	return _m.recorder
}

// DownloadImage mocks base method
func (_m *MockDownloader) DownloadImage(_param0 *url.URL) ([]byte, error) {
	ret := _m.ctrl.Call(_m, "DownloadImage", _param0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadImage indicates an expected call of DownloadImage
func (_mr *MockDownloaderMockRecorder) DownloadImage(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DownloadImage", reflect.TypeOf((*MockDownloader)(nil).DownloadImage), arg0)
}
